// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Preepex.Core.Domain.Entities
{
    public partial class Discountrequirement
    {
        public Discountrequirement()
        {
            InverseParent = new HashSet<Discountrequirement>();
        }

        public int Id { get; set; }
        public int DiscountId { get; set; }
        public int? ParentId { get; set; }
        public string DiscountRequirementRuleSystemName { get; set; }
        public int? InteractionTypeId { get; set; }
        public bool IsGroup { get; set; }

        public virtual Discount Discount { get; set; }
        public virtual Discountrequirement Parent { get; set; }
        public virtual ICollection<Discountrequirement> InverseParent { get; set; }
    }
}