// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Preepex.Core.Domain.Entities
{
    public partial class Externalauthenticationrecord
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string Email { get; set; }
        public string ExternalIdentifier { get; set; }
        public string ExternalDisplayIdentifier { get; set; }
        public string OauthToken { get; set; }
        public string OauthAccessToken { get; set; }
        public string ProviderSystemName { get; set; }

        public virtual Customer Customer { get; set; }
    }
}