// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Preepex.Core.Domain.Entities
{
    public partial class ForumsPrivatemessage
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Text { get; set; }
        public int FromCustomerId { get; set; }
        public int ToCustomerId { get; set; }
        public int StoreId { get; set; }
        public bool IsRead { get; set; }
        public bool IsDeletedByAuthor { get; set; }
        public bool IsDeletedByRecipient { get; set; }
        public DateTime CreatedOnUtc { get; set; }

        [NotMapped]
        public virtual Customer FromCustomer { get; set; }

        [NotMapped]
        public virtual Customer ToCustomer { get; set; }
    }
}