// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Preepex.Core.Domain.Entities.Common;
using System;
using System.Collections.Generic;

namespace Preepex.Core.Domain.Entities
{
    public partial class Productreview : BaseEntity<int>
    {
        public Productreview()
        {
            ProductreviewReviewtypeMapping = new HashSet<ProductreviewReviewtypeMapping>();
            Productreviewhelpfulness = new HashSet<Productreviewhelpfulness>();
        }

        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int ProductId { get; set; }
        public int StoreId { get; set; }
        public bool IsApproved { get; set; }
        public string Title { get; set; }
        public string ReviewText { get; set; }
        public string ReplyText { get; set; }
        public bool CustomerNotifiedOfReply { get; set; }
        public int Rating { get; set; }
        public int HelpfulYesTotal { get; set; }
        public int HelpfulNoTotal { get; set; }
        public DateTime CreatedOnUtc { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
        public virtual ICollection<ProductreviewReviewtypeMapping> ProductreviewReviewtypeMapping { get; set; }
        public virtual ICollection<Productreviewhelpfulness> Productreviewhelpfulness { get; set; }
    }
}