// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Preepex.Core.Domain.Entities
{
    public partial class Productattribute
    {
        public Productattribute()
        {
            PredeFinedProductAttributeValue = new HashSet<Predefinedproductattributevalue>();
            ProductProductattributeMapping = new HashSet<ProductProductattributeMapping>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Predefinedproductattributevalue> PredeFinedProductAttributeValue { get; set; }
        public virtual ICollection<ProductProductattributeMapping> ProductProductattributeMapping { get; set; }
    }
}