// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Preepex.Core.Domain.Entities.Common;
using Preepex.Core.Domain.Localization;
using System.Collections.Generic;

namespace Preepex.Core.Domain.Entities
{
    public partial class Specificationattributegroup : BaseEntity<int>, ILocalizedEntity
    {
        public Specificationattributegroup()
        {
            SpecificationAttribute = new HashSet<Specificationattribute>();
        }

        public string Name { get; set; }
        public int DisplayOrder { get; set; }

        public virtual ICollection<Specificationattribute> SpecificationAttribute { get; set; }
    }
}