// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Preepex.Core.Domain.Entities.Common;
using Preepex.Core.Domain.Localization;
using System;
using System.Collections.Generic;

namespace Preepex.Core.Domain.Entities
{
    public partial class Store: BaseEntity<int>, ILocalizedEntity
    {
        public Store()
        {
            BlogComment = new HashSet<BlogComment>();
            NewsComment = new HashSet<NewsComment>();
            ProductReview = new HashSet<Productreview>();
            StoreMapping = new HashSet<Storemapping>();
        }

        public string Name { get; set; }
        public string Url { get; set; }
        public string Hosts { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyPhoneNumber { get; set; }
        public string CompanyVat { get; set; }
        public bool SslEnabled { get; set; }
        public int DefaultLanguageId { get; set; }
        public int DisplayOrder { get; set; }

        public virtual ICollection<BlogComment> BlogComment { get; set; }
        public virtual ICollection<NewsComment> NewsComment { get; set; }
        public virtual ICollection<Productreview> ProductReview { get; set; }
        public virtual ICollection<Storemapping> StoreMapping { get; set; }
    }
}