// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Swiftrade.Core.Domain.Entities.Common;
using System;
using System.Collections.Generic;

namespace Swiftrade.Core.Domain.Entities
{
    public partial class Country : BaseEntity<int>
    {
        public Country()
        {
            Address = new HashSet<NopAddress>();
            StateProvince = new HashSet<StateProvince>();
            ShippingMethod = new HashSet<Shippingmethod>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string TwoLetterIsoCode { get; set; }
        public string ThreeLetterIsoCode { get; set; }
        public bool AllowsBilling { get; set; }
        public bool AllowsShipping { get; set; }
        public int NumericIsoCode { get; set; }
        public bool SubjectToVat { get; set; }
        public bool Published { get; set; }
        public int DisplayOrder { get; set; }
        public bool LimitedToStores { get; set; }


        public virtual ICollection<NopAddress> Address { get; set; }
        public virtual ICollection<StateProvince> StateProvince { get; set; }

        public virtual ICollection<Shippingmethod> ShippingMethod { get; set; }
    }
}