// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Swiftrade.Core.Domain.Entities.Common;
using System;
using System.Collections.Generic;

namespace Swiftrade.Core.Domain.Entities
{
    public partial class Customerrole : BaseEntity<int>
    {
        public Customerrole()
        {
            AclRecord = new HashSet<Aclrecord>();
            Tierprice = new HashSet<Tierprice>();
            Customer = new HashSet<Customer>();
            PermissionRecord = new HashSet<Permissionrecord>();
        }
        public string Name { get; set; }
        public string SystemName { get; set; }
        public bool FreeShipping { get; set; }
        public bool TaxExempt { get; set; }
        public bool Active { get; set; }
        public bool IsSystemRole { get; set; }
        public bool EnablePasswordLifetime { get; set; }
        public bool OverrideTaxDisplayType { get; set; }
        public int DefaultTaxDisplayTypeId { get; set; }
        public int PurchasedWithProductId { get; set; }
        public int CustomerId { get; set; }

        public virtual ICollection<Aclrecord> AclRecord { get; set; }
        public virtual ICollection<Tierprice> Tierprice { get; set; }

        public virtual ICollection<Customer> Customer { get; set; }
        public virtual ICollection<Permissionrecord> PermissionRecord { get; set; }
    }
}