// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Swiftrade.Core.Domain.Entities.Common;
using Swiftrade.Core.Domain.Localization;

namespace Swiftrade.Core.Domain.Entities
{
    public partial class Deliverydate : BaseEntity<int>, ILocalizedEntity
    {
        public string Name { get; set; }
        public int DisplayOrder { get; set; }
    }
}