// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Swiftrade.Core.Domain.Entities
{
    public partial class Discount
    {
        public Discount()
        {
            DiscountRequirement = new HashSet<Discountrequirement>();
            DiscountUsageHistory = new HashSet<Discountusagehistory>();
            Category = new HashSet<Category>();
            Manufacturer = new HashSet<Manufacturer>();
            Product = new HashSet<Product>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string CouponCode { get; set; }
        public string AdminComment { get; set; }
        public int DiscountTypeId { get; set; }
        public bool UsePercentage { get; set; }
        public decimal DiscountPercentage { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal? MaximumDiscountAmount { get; set; }
        public DateTime? StartDateUtc { get; set; }
        public DateTime? EndDateUtc { get; set; }
        public bool RequiresCouponCode { get; set; }
        public bool IsCumulative { get; set; }
        public int DiscountLimitationId { get; set; }
        public int LimitationTimes { get; set; }
        public int? MaximumDiscountedQuantity { get; set; }
        public bool AppliedToSubCategories { get; set; }

        public virtual ICollection<Discountrequirement> DiscountRequirement { get; set; }
        public virtual ICollection<Discountusagehistory> DiscountUsageHistory { get; set; }

        public virtual ICollection<Category> Category { get; set; }
        public virtual ICollection<Manufacturer> Manufacturer { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}