// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Swiftrade.Core.Domain.Entities
{
    public partial class ForumsPost
    {
        public ForumsPost()
        {
            ForumsPostvote = new HashSet<ForumsPostvote>();
        }

        public int Id { get; set; }
        public string Text { get; set; }
        public string Ipaddress { get; set; }
        public int CustomerId { get; set; }
        public int TopicId { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public DateTime UpdatedOnUtc { get; set; }
        public int VoteCount { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual ForumsTopic Topic { get; set; }
        public virtual ICollection<ForumsPostvote> ForumsPostvote { get; set; }
    }
}