// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Swiftrade.Core.Domain.Entities.Common;
using System;

namespace Swiftrade.Core.Domain.Entities
{
    public partial class GenericAttribute : BaseEntity<int>
    {
        public string KeyGroup { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public int EntityId { get; set; }
        public int StoreId { get; set; }
        public DateTime? CreatedOrUpdatedDateUtc { get; set; }
    }
}