// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Swiftrade.Core.Domain.Entities.Common;
using Swiftrade.Core.Domain.Interfaces;
using System.Collections.Generic;

namespace Swiftrade.Core.Domain.Entities
{
    public partial class Language : BaseEntity<int>, IStoreMappingSupported
    {
        public Language()
        {
            BlogPost = new HashSet<Blogpost>();
            LocaleStringResource = new HashSet<LocaleStringResource>();
            LocalizedProperty = new HashSet<Localizedproperty>();
            News = new HashSet<News>();
            Poll = new HashSet<Poll>();
        }

        public string Name { get; set; }
        public string LanguageCulture { get; set; }
        public string UniqueSeoCode { get; set; }
        public string FlagImageFileName { get; set; }
        public bool Rtl { get; set; }
        public bool LimitedToStores { get; set; }
        public int DefaultCurrencyId { get; set; }
        public bool Published { get; set; }
        public int DisplayOrder { get; set; }

        public virtual ICollection<Blogpost> BlogPost { get; set; }
        public virtual ICollection<LocaleStringResource> LocaleStringResource { get; set; }
        public virtual ICollection<Localizedproperty> LocalizedProperty { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<Poll> Poll { get; set; }
    }
}