// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Swiftrade.Core.Domain.Entities.Common;
using Swiftrade.Core.Domain.Interfaces;
using Swiftrade.Core.Domain.Localization;
using System;
using System.Collections.Generic;

namespace Swiftrade.Core.Domain.Entities
{
    public partial class ProductTag : BaseEntity<int> , ILocalizedEntity, ISlugSupported
    {
        public ProductTag()
        {
            Product = new HashSet<Product>();
        }
        public string Name { get; set; }

        public virtual ICollection<Product> Product { get; set; }
    }
}