// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Swiftrade.Core.Domain.Entities
{
    public partial class Shipment
    {
        public Shipment()
        {
            ShipmentItem = new HashSet<Shipmentitem>();
        }

        public int Id { get; set; }
        public int OrderId { get; set; }
        public string TrackingNumber { get; set; }
        public decimal? TotalWeight { get; set; }
        public DateTime? ShippedDateUtc { get; set; }
        public DateTime? DeliveryDateUtc { get; set; }
        public string AdminComment { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public DateTime? ReadyForPickupDateUtc { get; set; }

        public virtual Order Order { get; set; }
        public virtual ICollection<Shipmentitem> ShipmentItem { get; set; }
    }
}