// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Swiftrade.Core.Domain.Entities.Common;
using Swiftrade.Core.Domain.Localization;
using System;
using System.Collections.Generic;

namespace Swiftrade.Core.Domain.Entities
{
    public partial class Specificationattribute : BaseEntity<int>, ILocalizedEntity
    {
        public Specificationattribute()
        {
            SpecificationAttributeOption = new HashSet<Specificationattributeoption>();
        }
        public string Name { get; set; }
        public int? SpecificationAttributeGroupId { get; set; }
        public int DisplayOrder { get; set; }

        public virtual Specificationattributegroup SpecificationAttributeGroup { get; set; }
        public virtual ICollection<Specificationattributeoption> SpecificationAttributeOption { get; set; }
    }
}